[package]
name = "tan_cli"
description = "The Tan CLI"
version = "0.5.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tanlang-org/tan_cli"
keywords = ["tan", "language", "cli"]
authors = ["George Moschovitis <gmosx@reizu.org>"]
edition = "2021"

[dependencies]
anyhow = "1"
clap = "4"
regex = "1"
once_cell = "1"
rustyline = "11.0.0"
tracing = "0.1"
tracing-subscriber = "0.3"
tan = { path = "../tan", version = "0.5" }
tan_fmt = { path = "../tan_fmt", version = "0.5" }
tan_lint = { path = "../tan_lint", version = "0.5" }

[[bin]]
name = "tan"
path = "src/main.rs"
