[package]
name = "tan_cli"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = "4"
rustyline = "10"
tan = { path = "../tan" }
tan_fmt = { path = "../tan_fmt" }

[[bin]]
name = "tan"
path = "src/main.rs"
