[package]
name = "tan-tools"
description = "CLI tools for the Tan Language"
version = "0.8.0"
license = "Apache-2.0"
repository = "https://github.com/tanlang-org/tan_cli"
keywords = ["tan", "language", "tools", "cli"]
authors = ["George Moschovitis <gmosx@reizu.org>"]
edition = "2021"

[dependencies]
anyhow = "1"
clap = "4"
rustyline = "11.0.0"
tracing = "0.1"
tracing-subscriber = "0.3"
tan = { path = "../tan", version = "0.8" }
tan-formatting = { path = "../tan-formatting", version = "0.8" }
tan-lints = { path = "../tan-lints", version = "0.8" }

[[bin]]
name = "tan"
path = "src/main.rs"
